//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class braveXML {
    
    private braveXMLModel modelField;
    
    private braveXMLNode[] nodeField;
    
    private braveXMLPath[] pathField;
    
    private braveXMLService serviceField;
    
    private braveXMLTrainType trainTypeField;
    
    private braveXMLVehicleType vehicleTypeField;
    
    private braveXMLPointsInterlocking pointsInterlockingField;
    
    /// <remarks/>
    public braveXMLModel model {
        get {
            return this.modelField;
        }
        set {
            this.modelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("node")]
    public braveXMLNode[] node {
        get {
            return this.nodeField;
        }
        set {
            this.nodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("path")]
    public braveXMLPath[] path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    public braveXMLService service {
        get {
            return this.serviceField;
        }
        set {
            this.serviceField = value;
        }
    }
    
    /// <remarks/>
    public braveXMLTrainType trainType {
        get {
            return this.trainTypeField;
        }
        set {
            this.trainTypeField = value;
        }
    }
    
    /// <remarks/>
    public braveXMLVehicleType vehicleType {
        get {
            return this.vehicleTypeField;
        }
        set {
            this.vehicleTypeField = value;
        }
    }
    
    /// <remarks/>
    public braveXMLPointsInterlocking pointsInterlocking {
        get {
            return this.pointsInterlockingField;
        }
        set {
            this.pointsInterlockingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLModel {
    
    private string nameField;
    
    private bool destroyedField;
    
    private string modelNameField;
    
    private System.DateTime modelBRaVEVersionField;
    
    private decimal modelScaleField;
    
    private decimal positionUncertaintyFixedField;
    
    private decimal positionUncertaintyRatioField;
    
    private decimal cbtcSafetyMarginField;
    
    private decimal pseudoMovingBlockSizeField;
    
    private decimal antennaCoverageField;
    
    private int signallLookaheadField;
    
    private bool signalLookaheadOnGreensField;
    
    private bool codedTrackcircuitsField;
    
    private string overlapSelectionTypeField;
    
    private bool disableLockingOnPointsField;
    
    private decimal wholeSimCumulativeEnergyField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool destroyed {
        get {
            return this.destroyedField;
        }
        set {
            this.destroyedField = value;
        }
    }
    
    /// <remarks/>
    public string modelName {
        get {
            return this.modelNameField;
        }
        set {
            this.modelNameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime modelBRaVEVersion {
        get {
            return this.modelBRaVEVersionField;
        }
        set {
            this.modelBRaVEVersionField = value;
        }
    }
    
    /// <remarks/>
    public decimal modelScale {
        get {
            return this.modelScaleField;
        }
        set {
            this.modelScaleField = value;
        }
    }
    
    /// <remarks/>
    public decimal positionUncertaintyFixed {
        get {
            return this.positionUncertaintyFixedField;
        }
        set {
            this.positionUncertaintyFixedField = value;
        }
    }
    
    /// <remarks/>
    public decimal positionUncertaintyRatio {
        get {
            return this.positionUncertaintyRatioField;
        }
        set {
            this.positionUncertaintyRatioField = value;
        }
    }
    
    /// <remarks/>
    public decimal cbtcSafetyMargin {
        get {
            return this.cbtcSafetyMarginField;
        }
        set {
            this.cbtcSafetyMarginField = value;
        }
    }
    
    /// <remarks/>
    public decimal pseudoMovingBlockSize {
        get {
            return this.pseudoMovingBlockSizeField;
        }
        set {
            this.pseudoMovingBlockSizeField = value;
        }
    }
    
    /// <remarks/>
    public decimal antennaCoverage {
        get {
            return this.antennaCoverageField;
        }
        set {
            this.antennaCoverageField = value;
        }
    }
    
    /// <remarks/>
    public int signallLookahead {
        get {
            return this.signallLookaheadField;
        }
        set {
            this.signallLookaheadField = value;
        }
    }
    
    /// <remarks/>
    public bool signalLookaheadOnGreens {
        get {
            return this.signalLookaheadOnGreensField;
        }
        set {
            this.signalLookaheadOnGreensField = value;
        }
    }
    
    /// <remarks/>
    public bool codedTrackcircuits {
        get {
            return this.codedTrackcircuitsField;
        }
        set {
            this.codedTrackcircuitsField = value;
        }
    }
    
    /// <remarks/>
    public string overlapSelectionType {
        get {
            return this.overlapSelectionTypeField;
        }
        set {
            this.overlapSelectionTypeField = value;
        }
    }
    
    /// <remarks/>
    public bool disableLockingOnPoints {
        get {
            return this.disableLockingOnPointsField;
        }
        set {
            this.disableLockingOnPointsField = value;
        }
    }
    
    /// <remarks/>
    public decimal wholeSimCumulativeEnergy {
        get {
            return this.wholeSimCumulativeEnergyField;
        }
        set {
            this.wholeSimCumulativeEnergyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLNode {
    
    private string nameField;
    
    private bool destroyedField;
    
    private bool baliseField;
    
    private string baliseTypeField;
    
    private string antennaTypeField;
    
    private string axleCounterTypeField;
    
    private string magnetTypeField;
    
    private string operationalControlPointTypeField;
    
    private braveXMLNodePoint pointField;
    
    private braveXMLNodeNetPoint netPointField;
    
    private decimal kilometreField;
    
    private bool sightingDistanceField;
    
    private bool releaseContactField;
    
    private bool aspectTriggerField;
    
    private bool presignalField;
    
    private bool with1000HzMagnetField;
    
    private bool inductorStartField;
    
    private decimal kilometreChangeField;
    
    private bool stationBorderField;
    
    private bool stationField;
    
    private string stationNameField;
    
    private bool bufferStopField;
    
    private bool overlapField;
    
    private bool speedBoardField;
    
    private bool signalField;
    
    private string pathNamesField;
    
    private string referenceNodeNameField;
    
    private string connectionPointTypeField;
    
    private string insulationJointTypeField;
    
    private decimal lengthField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool destroyed {
        get {
            return this.destroyedField;
        }
        set {
            this.destroyedField = value;
        }
    }
    
    /// <remarks/>
    public bool balise {
        get {
            return this.baliseField;
        }
        set {
            this.baliseField = value;
        }
    }
    
    /// <remarks/>
    public string baliseType {
        get {
            return this.baliseTypeField;
        }
        set {
            this.baliseTypeField = value;
        }
    }
    
    /// <remarks/>
    public string antennaType {
        get {
            return this.antennaTypeField;
        }
        set {
            this.antennaTypeField = value;
        }
    }
    
    /// <remarks/>
    public string axleCounterType {
        get {
            return this.axleCounterTypeField;
        }
        set {
            this.axleCounterTypeField = value;
        }
    }
    
    /// <remarks/>
    public string magnetType {
        get {
            return this.magnetTypeField;
        }
        set {
            this.magnetTypeField = value;
        }
    }
    
    /// <remarks/>
    public string operationalControlPointType {
        get {
            return this.operationalControlPointTypeField;
        }
        set {
            this.operationalControlPointTypeField = value;
        }
    }
    
    /// <remarks/>
    public braveXMLNodePoint point {
        get {
            return this.pointField;
        }
        set {
            this.pointField = value;
        }
    }
    
    /// <remarks/>
    public braveXMLNodeNetPoint netPoint {
        get {
            return this.netPointField;
        }
        set {
            this.netPointField = value;
        }
    }
    
    /// <remarks/>
    public decimal kilometre {
        get {
            return this.kilometreField;
        }
        set {
            this.kilometreField = value;
        }
    }
    
    /// <remarks/>
    public bool sightingDistance {
        get {
            return this.sightingDistanceField;
        }
        set {
            this.sightingDistanceField = value;
        }
    }
    
    /// <remarks/>
    public bool releaseContact {
        get {
            return this.releaseContactField;
        }
        set {
            this.releaseContactField = value;
        }
    }
    
    /// <remarks/>
    public bool aspectTrigger {
        get {
            return this.aspectTriggerField;
        }
        set {
            this.aspectTriggerField = value;
        }
    }
    
    /// <remarks/>
    public bool presignal {
        get {
            return this.presignalField;
        }
        set {
            this.presignalField = value;
        }
    }
    
    /// <remarks/>
    public bool with1000HzMagnet {
        get {
            return this.with1000HzMagnetField;
        }
        set {
            this.with1000HzMagnetField = value;
        }
    }
    
    /// <remarks/>
    public bool inductorStart {
        get {
            return this.inductorStartField;
        }
        set {
            this.inductorStartField = value;
        }
    }
    
    /// <remarks/>
    public decimal kilometreChange {
        get {
            return this.kilometreChangeField;
        }
        set {
            this.kilometreChangeField = value;
        }
    }
    
    /// <remarks/>
    public bool stationBorder {
        get {
            return this.stationBorderField;
        }
        set {
            this.stationBorderField = value;
        }
    }
    
    /// <remarks/>
    public bool station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
    
    /// <remarks/>
    public string stationName {
        get {
            return this.stationNameField;
        }
        set {
            this.stationNameField = value;
        }
    }
    
    /// <remarks/>
    public bool bufferStop {
        get {
            return this.bufferStopField;
        }
        set {
            this.bufferStopField = value;
        }
    }
    
    /// <remarks/>
    public bool overlap {
        get {
            return this.overlapField;
        }
        set {
            this.overlapField = value;
        }
    }
    
    /// <remarks/>
    public bool speedBoard {
        get {
            return this.speedBoardField;
        }
        set {
            this.speedBoardField = value;
        }
    }
    
    /// <remarks/>
    public bool signal {
        get {
            return this.signalField;
        }
        set {
            this.signalField = value;
        }
    }
    
    /// <remarks/>
    public string pathNames {
        get {
            return this.pathNamesField;
        }
        set {
            this.pathNamesField = value;
        }
    }
    
    /// <remarks/>
    public string referenceNodeName {
        get {
            return this.referenceNodeNameField;
        }
        set {
            this.referenceNodeNameField = value;
        }
    }
    
    /// <remarks/>
    public string connectionPointType {
        get {
            return this.connectionPointTypeField;
        }
        set {
            this.connectionPointTypeField = value;
        }
    }
    
    /// <remarks/>
    public string insulationJointType {
        get {
            return this.insulationJointTypeField;
        }
        set {
            this.insulationJointTypeField = value;
        }
    }
    
    /// <remarks/>
    public decimal length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLNodePoint {
    
    private decimal xField;
    
    private decimal yField;
    
    /// <remarks/>
    public decimal x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public decimal y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLNodeNetPoint {
    
    private decimal xField;
    
    private decimal yField;
    
    /// <remarks/>
    public decimal x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public decimal y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLPath {
    
    private string nameField;
    
    private bool destroyedField;
    
    private decimal lengthField;
    
    private decimal vMaxField;
    
    private decimal vMaxRField;
    
    private decimal vMax_2Field;
    
    private decimal vMaxR_2Field;
    
    private decimal gradientField;
    
    private bool bidirectionalField;
    
    private decimal tunnelCrossSectionField;
    
    private decimal radiusField;
    
    private string noteField;
    
    private string zoneField;
    
    private string startNodeNameField;
    
    private string endNodeNameField;
    
    private bool segmentFaultField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool destroyed {
        get {
            return this.destroyedField;
        }
        set {
            this.destroyedField = value;
        }
    }
    
    /// <remarks/>
    public decimal length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    public decimal vMax {
        get {
            return this.vMaxField;
        }
        set {
            this.vMaxField = value;
        }
    }
    
    /// <remarks/>
    public decimal vMaxR {
        get {
            return this.vMaxRField;
        }
        set {
            this.vMaxRField = value;
        }
    }
    
    /// <remarks/>
    public decimal vMax_2 {
        get {
            return this.vMax_2Field;
        }
        set {
            this.vMax_2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal vMaxR_2 {
        get {
            return this.vMaxR_2Field;
        }
        set {
            this.vMaxR_2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal gradient {
        get {
            return this.gradientField;
        }
        set {
            this.gradientField = value;
        }
    }
    
    /// <remarks/>
    public bool bidirectional {
        get {
            return this.bidirectionalField;
        }
        set {
            this.bidirectionalField = value;
        }
    }
    
    /// <remarks/>
    public decimal tunnelCrossSection {
        get {
            return this.tunnelCrossSectionField;
        }
        set {
            this.tunnelCrossSectionField = value;
        }
    }
    
    /// <remarks/>
    public decimal radius {
        get {
            return this.radiusField;
        }
        set {
            this.radiusField = value;
        }
    }
    
    /// <remarks/>
    public string note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    public string zone {
        get {
            return this.zoneField;
        }
        set {
            this.zoneField = value;
        }
    }
    
    /// <remarks/>
    public string startNodeName {
        get {
            return this.startNodeNameField;
        }
        set {
            this.startNodeNameField = value;
        }
    }
    
    /// <remarks/>
    public string endNodeName {
        get {
            return this.endNodeNameField;
        }
        set {
            this.endNodeNameField = value;
        }
    }
    
    /// <remarks/>
    public bool segmentFault {
        get {
            return this.segmentFaultField;
        }
        set {
            this.segmentFaultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLService {
    
    private string nameField;
    
    private bool destroyedField;
    
    private int trainNumberField;
    
    private string _classField;
    
    private string trainTypeNameField;
    
    private int lineField;
    
    private int opDayField;
    
    private int extOpdayField;
    
    private System.DateTime fromDateField;
    
    private System.DateTime toDateField;
    
    private bool pOST_1_13_15_SERVICEField;
    
    private string serviceEntriesMapField;
    
    private braveXMLServiceServiceNodes[] serviceNodesField;
    
    private decimal startDistanceOffsetField;
    
    private bool suppressDCSPlanningField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool destroyed {
        get {
            return this.destroyedField;
        }
        set {
            this.destroyedField = value;
        }
    }
    
    /// <remarks/>
    public int trainNumber {
        get {
            return this.trainNumberField;
        }
        set {
            this.trainNumberField = value;
        }
    }
    
    /// <remarks/>
    public string _class {
        get {
            return this._classField;
        }
        set {
            this._classField = value;
        }
    }
    
    /// <remarks/>
    public string trainTypeName {
        get {
            return this.trainTypeNameField;
        }
        set {
            this.trainTypeNameField = value;
        }
    }
    
    /// <remarks/>
    public int line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }
    
    /// <remarks/>
    public int opDay {
        get {
            return this.opDayField;
        }
        set {
            this.opDayField = value;
        }
    }
    
    /// <remarks/>
    public int extOpday {
        get {
            return this.extOpdayField;
        }
        set {
            this.extOpdayField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime fromDate {
        get {
            return this.fromDateField;
        }
        set {
            this.fromDateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime toDate {
        get {
            return this.toDateField;
        }
        set {
            this.toDateField = value;
        }
    }
    
    /// <remarks/>
    public bool POST_1_13_15_SERVICE {
        get {
            return this.pOST_1_13_15_SERVICEField;
        }
        set {
            this.pOST_1_13_15_SERVICEField = value;
        }
    }
    
    /// <remarks/>
    public string serviceEntriesMap {
        get {
            return this.serviceEntriesMapField;
        }
        set {
            this.serviceEntriesMapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("serviceNodes")]
    public braveXMLServiceServiceNodes[] serviceNodes {
        get {
            return this.serviceNodesField;
        }
        set {
            this.serviceNodesField = value;
        }
    }
    
    /// <remarks/>
    public decimal startDistanceOffset {
        get {
            return this.startDistanceOffsetField;
        }
        set {
            this.startDistanceOffsetField = value;
        }
    }
    
    /// <remarks/>
    public bool suppressDCSPlanning {
        get {
            return this.suppressDCSPlanningField;
        }
        set {
            this.suppressDCSPlanningField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLServiceServiceNodes {
    
    private int minStopTimeField;
    
    private string nextNodeNameField;
    
    private string nodeNameField;
    
    private int regularRunningTimeField;
    
    private braveXMLServiceServiceNodesRequestedDeparture requestedDepartureField;
    
    private string stationIdField;
    
    private int stopTimeField;
    
    private string trackIdField;
    
    private string typeField;
    
    /// <remarks/>
    public int minStopTime {
        get {
            return this.minStopTimeField;
        }
        set {
            this.minStopTimeField = value;
        }
    }
    
    /// <remarks/>
    public string nextNodeName {
        get {
            return this.nextNodeNameField;
        }
        set {
            this.nextNodeNameField = value;
        }
    }
    
    /// <remarks/>
    public string nodeName {
        get {
            return this.nodeNameField;
        }
        set {
            this.nodeNameField = value;
        }
    }
    
    /// <remarks/>
    public int regularRunningTime {
        get {
            return this.regularRunningTimeField;
        }
        set {
            this.regularRunningTimeField = value;
        }
    }
    
    /// <remarks/>
    public braveXMLServiceServiceNodesRequestedDeparture requestedDeparture {
        get {
            return this.requestedDepartureField;
        }
        set {
            this.requestedDepartureField = value;
        }
    }
    
    /// <remarks/>
    public string stationId {
        get {
            return this.stationIdField;
        }
        set {
            this.stationIdField = value;
        }
    }
    
    /// <remarks/>
    public int stopTime {
        get {
            return this.stopTimeField;
        }
        set {
            this.stopTimeField = value;
        }
    }
    
    /// <remarks/>
    public string trackId {
        get {
            return this.trackIdField;
        }
        set {
            this.trackIdField = value;
        }
    }
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLServiceServiceNodesRequestedDeparture {
    
    private int hoursField;
    
    private int minsField;
    
    private int secondsField;
    
    private int millisecondsField;
    
    /// <remarks/>
    public int hours {
        get {
            return this.hoursField;
        }
        set {
            this.hoursField = value;
        }
    }
    
    /// <remarks/>
    public int mins {
        get {
            return this.minsField;
        }
        set {
            this.minsField = value;
        }
    }
    
    /// <remarks/>
    public int seconds {
        get {
            return this.secondsField;
        }
        set {
            this.secondsField = value;
        }
    }
    
    /// <remarks/>
    public int milliseconds {
        get {
            return this.millisecondsField;
        }
        set {
            this.millisecondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLTrainType {
    
    private string nameField;
    
    private bool destroyedField;
    
    private int trainNumberField;
    
    private decimal maxSpeedField;
    
    private decimal brakesField;
    
    private string _classField;
    
    private int maxTractionForceField;
    
    private decimal maxAccelerationField;
    
    private decimal powerField;
    
    private decimal lambdaField;
    
    private decimal genRateField;
    
    private decimal regenRateField;
    
    private bool cbtcField;
    
    private bool moving_blockField;
    
    private bool constantPowerBrakingField;
    
    private bool constantPowerTractionField;
    
    private braveXMLTrainTypeVTypeEntries vTypeEntriesField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool destroyed {
        get {
            return this.destroyedField;
        }
        set {
            this.destroyedField = value;
        }
    }
    
    /// <remarks/>
    public int trainNumber {
        get {
            return this.trainNumberField;
        }
        set {
            this.trainNumberField = value;
        }
    }
    
    /// <remarks/>
    public decimal maxSpeed {
        get {
            return this.maxSpeedField;
        }
        set {
            this.maxSpeedField = value;
        }
    }
    
    /// <remarks/>
    public decimal brakes {
        get {
            return this.brakesField;
        }
        set {
            this.brakesField = value;
        }
    }
    
    /// <remarks/>
    public string _class {
        get {
            return this._classField;
        }
        set {
            this._classField = value;
        }
    }
    
    /// <remarks/>
    public int maxTractionForce {
        get {
            return this.maxTractionForceField;
        }
        set {
            this.maxTractionForceField = value;
        }
    }
    
    /// <remarks/>
    public decimal maxAcceleration {
        get {
            return this.maxAccelerationField;
        }
        set {
            this.maxAccelerationField = value;
        }
    }
    
    /// <remarks/>
    public decimal power {
        get {
            return this.powerField;
        }
        set {
            this.powerField = value;
        }
    }
    
    /// <remarks/>
    public decimal lambda {
        get {
            return this.lambdaField;
        }
        set {
            this.lambdaField = value;
        }
    }
    
    /// <remarks/>
    public decimal genRate {
        get {
            return this.genRateField;
        }
        set {
            this.genRateField = value;
        }
    }
    
    /// <remarks/>
    public decimal regenRate {
        get {
            return this.regenRateField;
        }
        set {
            this.regenRateField = value;
        }
    }
    
    /// <remarks/>
    public bool cbtc {
        get {
            return this.cbtcField;
        }
        set {
            this.cbtcField = value;
        }
    }
    
    /// <remarks/>
    public bool moving_block {
        get {
            return this.moving_blockField;
        }
        set {
            this.moving_blockField = value;
        }
    }
    
    /// <remarks/>
    public bool constantPowerBraking {
        get {
            return this.constantPowerBrakingField;
        }
        set {
            this.constantPowerBrakingField = value;
        }
    }
    
    /// <remarks/>
    public bool constantPowerTraction {
        get {
            return this.constantPowerTractionField;
        }
        set {
            this.constantPowerTractionField = value;
        }
    }
    
    /// <remarks/>
    public braveXMLTrainTypeVTypeEntries vTypeEntries {
        get {
            return this.vTypeEntriesField;
        }
        set {
            this.vTypeEntriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLTrainTypeVTypeEntries {
    
    private decimal accelerationFactorField;
    
    private decimal deccelerationFactorField;
    
    private string typeNameField;
    
    /// <remarks/>
    public decimal accelerationFactor {
        get {
            return this.accelerationFactorField;
        }
        set {
            this.accelerationFactorField = value;
        }
    }
    
    /// <remarks/>
    public decimal deccelerationFactor {
        get {
            return this.deccelerationFactorField;
        }
        set {
            this.deccelerationFactorField = value;
        }
    }
    
    /// <remarks/>
    public string typeName {
        get {
            return this.typeNameField;
        }
        set {
            this.typeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLVehicleType {
    
    private string nameField;
    
    private bool destroyedField;
    
    private decimal vMaxField;
    
    private string tractionTypeField;
    
    private decimal lengthField;
    
    private decimal weightField;
    
    private decimal massSurchargeField;
    
    private braveXMLVehicleTypePowerEntries[] powerEntriesField;
    
    private string rollingResistanceTypeField;
    
    private decimal rollingResistanceConstantCoefficientField;
    
    private decimal rollingResistanceLinearCoefficientField;
    
    private decimal rollingResistanceSquareCoefficientField;
    
    private braveXMLVehicleTypeRollingResistanceTable[] rollingResistanceTableField;
    
    private int carCountField;
    
    private int numberOfPassengerSeatsField;
    
    private int freightKilosField;
    
    private string vehicleTypeTypeField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool destroyed {
        get {
            return this.destroyedField;
        }
        set {
            this.destroyedField = value;
        }
    }
    
    /// <remarks/>
    public decimal vMax {
        get {
            return this.vMaxField;
        }
        set {
            this.vMaxField = value;
        }
    }
    
    /// <remarks/>
    public string tractionType {
        get {
            return this.tractionTypeField;
        }
        set {
            this.tractionTypeField = value;
        }
    }
    
    /// <remarks/>
    public decimal length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    public decimal weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    public decimal massSurcharge {
        get {
            return this.massSurchargeField;
        }
        set {
            this.massSurchargeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("powerEntries")]
    public braveXMLVehicleTypePowerEntries[] powerEntries {
        get {
            return this.powerEntriesField;
        }
        set {
            this.powerEntriesField = value;
        }
    }
    
    /// <remarks/>
    public string rollingResistanceType {
        get {
            return this.rollingResistanceTypeField;
        }
        set {
            this.rollingResistanceTypeField = value;
        }
    }
    
    /// <remarks/>
    public decimal rollingResistanceConstantCoefficient {
        get {
            return this.rollingResistanceConstantCoefficientField;
        }
        set {
            this.rollingResistanceConstantCoefficientField = value;
        }
    }
    
    /// <remarks/>
    public decimal rollingResistanceLinearCoefficient {
        get {
            return this.rollingResistanceLinearCoefficientField;
        }
        set {
            this.rollingResistanceLinearCoefficientField = value;
        }
    }
    
    /// <remarks/>
    public decimal rollingResistanceSquareCoefficient {
        get {
            return this.rollingResistanceSquareCoefficientField;
        }
        set {
            this.rollingResistanceSquareCoefficientField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rollingResistanceTable")]
    public braveXMLVehicleTypeRollingResistanceTable[] rollingResistanceTable {
        get {
            return this.rollingResistanceTableField;
        }
        set {
            this.rollingResistanceTableField = value;
        }
    }
    
    /// <remarks/>
    public int carCount {
        get {
            return this.carCountField;
        }
        set {
            this.carCountField = value;
        }
    }
    
    /// <remarks/>
    public int numberOfPassengerSeats {
        get {
            return this.numberOfPassengerSeatsField;
        }
        set {
            this.numberOfPassengerSeatsField = value;
        }
    }
    
    /// <remarks/>
    public int freightKilos {
        get {
            return this.freightKilosField;
        }
        set {
            this.freightKilosField = value;
        }
    }
    
    /// <remarks/>
    public string vehicleTypeType {
        get {
            return this.vehicleTypeTypeField;
        }
        set {
            this.vehicleTypeTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLVehicleTypePowerEntries {
    
    private string typeField;
    
    private decimal firstFixPointVField;
    
    private decimal firstFixPointFField;
    
    private decimal intermediateFixPointVField;
    
    private decimal intermediateFixPointFField;
    
    private decimal lastFixPointVField;
    
    private decimal lastFixPointFField;
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public decimal firstFixPointV {
        get {
            return this.firstFixPointVField;
        }
        set {
            this.firstFixPointVField = value;
        }
    }
    
    /// <remarks/>
    public decimal firstFixPointF {
        get {
            return this.firstFixPointFField;
        }
        set {
            this.firstFixPointFField = value;
        }
    }
    
    /// <remarks/>
    public decimal intermediateFixPointV {
        get {
            return this.intermediateFixPointVField;
        }
        set {
            this.intermediateFixPointVField = value;
        }
    }
    
    /// <remarks/>
    public decimal intermediateFixPointF {
        get {
            return this.intermediateFixPointFField;
        }
        set {
            this.intermediateFixPointFField = value;
        }
    }
    
    /// <remarks/>
    public decimal lastFixPointV {
        get {
            return this.lastFixPointVField;
        }
        set {
            this.lastFixPointVField = value;
        }
    }
    
    /// <remarks/>
    public decimal lastFixPointF {
        get {
            return this.lastFixPointFField;
        }
        set {
            this.lastFixPointFField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLVehicleTypeRollingResistanceTable {
    
    private decimal vField;
    
    private decimal fField;
    
    /// <remarks/>
    public decimal v {
        get {
            return this.vField;
        }
        set {
            this.vField = value;
        }
    }
    
    /// <remarks/>
    public decimal f {
        get {
            return this.fField;
        }
        set {
            this.fField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class braveXMLPointsInterlocking {
    
    private string nameField;
    
    private bool destroyedField;
    
    private string nodeNameField;
    
    private bool switchFlagField;
    
    private int switchTimeField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool destroyed {
        get {
            return this.destroyedField;
        }
        set {
            this.destroyedField = value;
        }
    }
    
    /// <remarks/>
    public string nodeName {
        get {
            return this.nodeNameField;
        }
        set {
            this.nodeNameField = value;
        }
    }
    
    /// <remarks/>
    public bool switchFlag {
        get {
            return this.switchFlagField;
        }
        set {
            this.switchFlagField = value;
        }
    }
    
    /// <remarks/>
    public int switchTime {
        get {
            return this.switchTimeField;
        }
        set {
            this.switchTimeField = value;
        }
    }
}
